import type { RoleDefinition } from "./career";

const COMMON_LEVELS: RoleDefinition["levels"] = ["internship", "entry", "associate", "any"];

function role(definition: Omit<RoleDefinition, "levels"> & { levels?: RoleDefinition["levels"] }): RoleDefinition {
    return { ...definition, levels: definition.levels ?? COMMON_LEVELS };
}

export const EXTENDED_ROLES: RoleDefinition[] = [
    role({
        id: "strategy-analyst",
        title: "Strategy Analyst",
        track: "general",
        summary: "Research markets and business choices, structure ambiguous questions, and support leadership decisions with evidence.",
        interestTerms: ["research", "strategy", "consulting", "business", "market", "problem"],
        industryTerms: ["consulting", "professional services", "enterprise", "financial services"],
        evidenceTerms: ["market research", "competitive analysis", "financial analysis", "presentation", "problem solving", "data analysis"],
        educationTerms: ["mba", "business", "economics", "finance", "engineering", "management"],
        workStyles: ["Analytical", "Independent research", "Problem solving", "Persuasive communication"],
        expectedWork: ["Frame strategic questions and assumptions.", "Research markets, competitors, and operating models.", "Build analyses and decision-ready presentations.", "Track whether chosen initiatives deliver expected outcomes."],
        skills: ["Market research", "Competitive analysis", "Microsoft Excel", "Financial analysis", "Business presentation", "Problem solving"],
    }),
    role({
        id: "research-analyst",
        title: "Research Analyst",
        track: "analytics",
        summary: "Collect, validate, synthesize, and communicate primary and secondary research for business decisions.",
        interestTerms: ["research", "insight", "writing", "strategy", "data", "market"],
        industryTerms: ["consulting", "investment", "media", "professional services", "nonprofit"],
        evidenceTerms: ["research", "survey", "interview", "market research", "data analysis", "report", "presentation"],
        educationTerms: ["economics", "business", "social science", "statistics", "mba", "communications"],
        workStyles: ["Independent research", "Deep focus", "Analytical", "Writing and documentation"],
        expectedWork: ["Define research questions and credible sources.", "Collect and clean qualitative or quantitative evidence.", "Synthesize patterns, limitations, and implications.", "Write concise reports and present findings."],
        skills: ["Research design", "Market research", "Data analysis", "Microsoft Excel", "Report writing", "Presentation"],
    }),
    role({
        id: "customer-insights-analyst",
        title: "Customer Insights Analyst",
        track: "analytics",
        summary: "Combine customer research and behavioral data to explain needs, segments, satisfaction, and product opportunities.",
        interestTerms: ["customer", "research", "data", "insight", "user", "design"],
        industryTerms: ["consumer", "retail", "e-commerce", "saas", "banking", "telecommunications"],
        evidenceTerms: ["customer research", "user research", "survey", "analytics", "segmentation", "dashboard", "presentation"],
        educationTerms: ["marketing", "psychology", "business", "economics", "statistics", "mba"],
        workStyles: ["Analytical", "Customer-facing", "Independent research", "Cross-functional"],
        expectedWork: ["Design surveys, interviews, and customer analyses.", "Segment customers and diagnose behavior or satisfaction.", "Connect qualitative themes with product or commercial data.", "Recommend changes to product, service, or messaging."],
        skills: ["Customer research", "Survey design", "Segmentation", "Data analysis", "Power BI", "Presentation"],
    }),
    role({
        id: "ux-research-associate",
        title: "UX Research Associate",
        track: "product",
        summary: "Study users and workflows so product and design teams solve the right usability and experience problems.",
        interestTerms: ["customer", "user", "design", "research", "product", "experience"],
        industryTerms: ["consumer apps", "saas", "e-commerce", "healthcare", "education", "fintech"],
        evidenceTerms: ["user research", "interview", "usability", "survey", "user experience", "figma", "journey"],
        educationTerms: ["psychology", "design", "business", "human computer interaction", "sociology", "mba"],
        workStyles: ["Customer-facing", "Independent research", "Detail-oriented", "Cross-functional"],
        expectedWork: ["Plan interviews and usability studies.", "Recruit participants and conduct ethical research.", "Synthesize observations into needs and design implications.", "Share evidence with product, design, and engineering."],
        skills: ["User research", "Usability testing", "Interviewing", "Journey mapping", "Research synthesis", "Figma"],
    }),
    role({
        id: "project-coordinator",
        title: "Project Coordinator",
        track: "operations",
        summary: "Keep projects moving through plans, owners, dependencies, documentation, risk tracking, and stakeholder follow-through.",
        interestTerms: ["operations", "coordination", "project", "execution", "process", "business"],
        industryTerms: ["professional services", "consulting", "construction", "technology", "healthcare"],
        evidenceTerms: ["project management", "coordination", "documentation", "stakeholder", "timeline", "risk", "reporting"],
        educationTerms: ["business", "management", "engineering", "mba", "operations"],
        workStyles: ["Structured execution", "Cross-functional", "Detail-oriented", "Process ownership"],
        expectedWork: ["Maintain plans, milestones, owners, and meeting actions.", "Track dependencies, risks, and status changes.", "Prepare updates and keep documentation current.", "Escalate blockers and coordinate follow-through."],
        skills: ["Project management", "Planning", "Risk tracking", "Documentation", "Stakeholder management", "Microsoft Excel"],
    }),
    role({
        id: "pmo-analyst",
        title: "PMO Analyst",
        track: "operations",
        summary: "Support portfolio governance, project reporting, resource visibility, controls, and delivery standards.",
        interestTerms: ["operations", "project", "process", "quality", "data", "coordination"],
        industryTerms: ["consulting", "banking", "enterprise software", "government", "telecommunications"],
        evidenceTerms: ["project management", "reporting", "dashboard", "governance", "risk", "excel", "power bi"],
        educationTerms: ["business", "management", "engineering", "operations", "mba"],
        workStyles: ["Structured execution", "Quality and accuracy", "Analytical", "Writing and documentation"],
        expectedWork: ["Consolidate project status and portfolio dashboards.", "Maintain governance templates, risks, and decisions.", "Check data quality and delivery compliance.", "Support capacity, budget, and milestone reviews."],
        skills: ["PMO", "Project reporting", "Microsoft Excel", "Power BI", "Risk management", "Governance"],
    }),
    role({
        id: "sales-operations-analyst",
        title: "Sales Operations Analyst",
        track: "operations",
        summary: "Improve CRM data, pipeline reporting, forecasting, territory processes, and commercial team productivity.",
        interestTerms: ["sales", "data", "operations", "customer", "process", "business"],
        industryTerms: ["saas", "enterprise software", "professional services", "telecommunications", "manufacturing"],
        evidenceTerms: ["crm", "sales", "pipeline", "forecast", "excel", "power bi", "process improvement"],
        educationTerms: ["business", "marketing", "finance", "economics", "mba"],
        workStyles: ["Analytical", "Structured execution", "Cross-functional", "Quality and accuracy"],
        expectedWork: ["Maintain accurate CRM and pipeline data.", "Build forecasts and sales-performance reports.", "Improve lead routing, territories, and operating processes.", "Support reviews with actionable commercial insights."],
        skills: ["CRM", "Sales analytics", "Forecasting", "Microsoft Excel", "Power BI", "Process improvement"],
    }),
    role({
        id: "business-development-associate",
        title: "Business Development Associate",
        track: "marketing",
        summary: "Research prospects, open commercial conversations, qualify opportunities, and support proposals and partnerships.",
        interestTerms: ["sales", "partnership", "negotiation", "customer", "market", "growth"],
        industryTerms: ["saas", "consulting", "professional services", "fintech", "logistics"],
        evidenceTerms: ["sales", "business development", "market research", "presentation", "communication", "negotiation", "crm"],
        educationTerms: ["business", "marketing", "mba", "economics", "management"],
        workStyles: ["Customer-facing", "Persuasive communication", "Fast-paced", "Negotiation"],
        expectedWork: ["Research accounts and decision makers.", "Run outreach and qualify business needs.", "Coordinate demos, proposals, and follow-ups.", "Track pipeline and learn from conversion patterns."],
        skills: ["Business development", "Prospecting", "CRM", "Negotiation", "Presentation", "Market research"],
    }),
    role({
        id: "partnerships-associate",
        title: "Partnerships Associate",
        track: "general",
        summary: "Identify, evaluate, launch, and operate partnerships that create distribution, product, or customer value.",
        interestTerms: ["partnership", "negotiation", "strategy", "customer", "growth", "product"],
        industryTerms: ["fintech", "saas", "consumer apps", "media", "e-commerce"],
        evidenceTerms: ["partnership", "stakeholder", "market research", "negotiation", "project management", "presentation"],
        educationTerms: ["business", "marketing", "mba", "management", "economics"],
        workStyles: ["Customer-facing", "Cross-functional", "Negotiation", "Persuasive communication"],
        expectedWork: ["Map potential partners and strategic fit.", "Prepare outreach, business cases, and proposals.", "Coordinate legal, product, marketing, and launch work.", "Track partner performance and resolve operating issues."],
        skills: ["Partnerships", "Business cases", "Negotiation", "Stakeholder management", "Project management", "Communication"],
    }),
    role({
        id: "investment-research-analyst",
        title: "Investment Research Analyst",
        track: "finance",
        summary: "Research companies, sectors, financial performance, valuation, and risks to support investment decisions.",
        interestTerms: ["finance", "investing", "markets", "research", "data", "business"],
        industryTerms: ["capital markets", "investment management", "financial services", "banking"],
        evidenceTerms: ["financial analysis", "valuation", "market research", "economics", "excel", "financial modeling"],
        educationTerms: ["finance", "economics", "commerce", "accounting", "mba finance"],
        workStyles: ["Analytical", "Independent research", "Deep focus", "Writing and documentation"],
        expectedWork: ["Study sectors, companies, management, and catalysts.", "Analyze statements, forecasts, valuation, and risk.", "Maintain models and monitor new information.", "Write evidence-based investment notes."],
        skills: ["Equity research", "Financial modeling", "Valuation", "Microsoft Excel", "Accounting", "Report writing"],
    }),
    role({
        id: "credit-analyst",
        title: "Credit Analyst",
        track: "finance",
        summary: "Assess borrower financial strength, repayment capacity, industry risk, and credit terms.",
        interestTerms: ["finance", "risk", "banking", "analysis", "business", "quality"],
        industryTerms: ["banking", "financial services", "fintech", "insurance"],
        evidenceTerms: ["financial analysis", "credit", "risk", "accounting", "excel", "ratio analysis"],
        educationTerms: ["finance", "commerce", "accounting", "economics", "mba finance"],
        workStyles: ["Analytical", "Detail-oriented", "Quality and accuracy", "Structured execution"],
        expectedWork: ["Review borrower and industry information.", "Analyze statements, cash flow, ratios, and repayment ability.", "Document risks, mitigants, and recommended limits.", "Monitor portfolio signals and covenant compliance."],
        skills: ["Credit analysis", "Financial statements", "Ratio analysis", "Risk assessment", "Microsoft Excel", "Report writing"],
    }),
    role({
        id: "risk-compliance-analyst",
        title: "Risk & Compliance Analyst",
        track: "finance",
        summary: "Monitor controls, regulations, operational risks, incidents, and evidence needed for responsible business operations.",
        interestTerms: ["risk", "compliance", "quality", "finance", "process", "regulation"],
        industryTerms: ["banking", "fintech", "insurance", "healthcare", "government", "cybersecurity"],
        evidenceTerms: ["risk", "compliance", "audit", "controls", "documentation", "quality", "regulation"],
        educationTerms: ["finance", "law", "commerce", "business", "economics", "mba"],
        workStyles: ["Quality and accuracy", "Detail-oriented", "Structured execution", "Writing and documentation"],
        expectedWork: ["Maintain policies, controls, and evidence.", "Review transactions, processes, or incidents for risk.", "Track remediation and regulatory obligations.", "Prepare monitoring reports and escalation notes."],
        skills: ["Risk management", "Compliance", "Internal controls", "Audit support", "Documentation", "Data analysis"],
    }),
    role({
        id: "fp-and-a-analyst",
        title: "FP&A Analyst",
        track: "finance",
        summary: "Support budgeting, forecasting, management reporting, variance analysis, and business planning.",
        interestTerms: ["finance", "business", "numbers", "planning", "data", "strategy"],
        industryTerms: ["financial services", "saas", "manufacturing", "retail", "healthcare"],
        evidenceTerms: ["budget", "forecast", "variance", "financial analysis", "excel", "power bi", "reporting"],
        educationTerms: ["finance", "accounting", "commerce", "economics", "mba finance"],
        workStyles: ["Analytical", "Structured execution", "Detail-oriented", "Cross-functional"],
        expectedWork: ["Prepare budgets, forecasts, and scenario models.", "Explain actual-versus-plan variances.", "Build management reporting and business-driver views.", "Partner with teams on planning assumptions and decisions."],
        skills: ["FP&A", "Budgeting", "Forecasting", "Variance analysis", "Microsoft Excel", "Financial modeling"],
    }),
    role({
        id: "supply-chain-analyst",
        title: "Supply Chain Analyst",
        track: "operations",
        summary: "Analyze demand, inventory, service, capacity, and logistics to improve supply-chain decisions.",
        interestTerms: ["supply chain", "logistics", "operations", "data", "process", "planning"],
        industryTerms: ["logistics", "manufacturing", "retail", "fmcg", "automotive", "food"],
        evidenceTerms: ["inventory", "supply chain", "logistics", "forecast", "excel", "power bi", "operations"],
        educationTerms: ["operations", "supply chain", "engineering", "business", "mba"],
        workStyles: ["Analytical", "Structured execution", "Process ownership", "Problem solving"],
        expectedWork: ["Track demand, inventory, service, and lead-time metrics.", "Investigate shortages, excess, delays, and cost drivers.", "Support forecasts and operating plans.", "Coordinate improvement actions with suppliers and teams."],
        skills: ["Supply chain", "Inventory analysis", "Demand planning", "Microsoft Excel", "Power BI", "Process improvement"],
    }),
    role({
        id: "procurement-analyst",
        title: "Procurement Analyst",
        track: "operations",
        summary: "Support spend analysis, sourcing, supplier evaluation, negotiation preparation, and purchasing controls.",
        interestTerms: ["procurement", "supply chain", "negotiation", "operations", "data", "business"],
        industryTerms: ["manufacturing", "construction", "healthcare", "retail", "energy", "automotive"],
        evidenceTerms: ["procurement", "vendor", "supplier", "negotiation", "excel", "cost analysis", "contract"],
        educationTerms: ["operations", "supply chain", "business", "commerce", "engineering", "mba"],
        workStyles: ["Analytical", "Negotiation", "Detail-oriented", "Structured execution"],
        expectedWork: ["Analyze spend, demand, and supplier performance.", "Prepare sourcing comparisons and negotiation data.", "Maintain purchasing records and policy compliance.", "Coordinate vendors, users, finance, and legal."],
        skills: ["Procurement", "Spend analysis", "Vendor management", "Negotiation", "Microsoft Excel", "Contract basics"],
    }),
    role({
        id: "hr-operations-associate",
        title: "HR Operations Associate",
        track: "people",
        summary: "Run accurate employee lifecycle processes, HR records, queries, documentation, and people-service operations.",
        interestTerms: ["people", "workplace", "operations", "helping", "process", "quality"],
        industryTerms: ["hr", "professional services", "technology", "healthcare", "retail"],
        evidenceTerms: ["human resources", "hr operations", "onboarding", "documentation", "employee", "excel", "process"],
        educationTerms: ["human resources", "business", "management", "psychology", "commerce", "mba"],
        workStyles: ["Structured execution", "Detail-oriented", "Customer-facing", "Quality and accuracy"],
        expectedWork: ["Process onboarding, changes, leave, and exits.", "Maintain accurate employee records and documents.", "Resolve employee and manager queries.", "Track service metrics and improve HR workflows."],
        skills: ["HR operations", "Employee lifecycle", "HRIS", "Documentation", "Microsoft Excel", "Process improvement"],
    }),
    role({
        id: "people-analytics-associate",
        title: "People Analytics Associate",
        track: "people",
        summary: "Analyze workforce, hiring, engagement, retention, and performance data for better people decisions.",
        interestTerms: ["people", "data", "dashboard", "workplace", "research", "insight"],
        industryTerms: ["hr", "consulting", "technology", "professional services"],
        evidenceTerms: ["people analytics", "recruitment metrics", "excel", "power bi", "dashboard", "survey", "data analysis"],
        educationTerms: ["human resources", "analytics", "psychology", "business", "statistics", "mba"],
        workStyles: ["Analytical", "Quality and accuracy", "Independent research", "Cross-functional"],
        expectedWork: ["Prepare recurring workforce and hiring metrics.", "Analyze engagement, retention, diversity, or performance patterns.", "Build clear dashboards with governed definitions.", "Explain findings responsibly to HR and leaders."],
        skills: ["People analytics", "Microsoft Excel", "Power BI", "Survey analysis", "Data visualization", "HR metrics"],
    }),
    role({
        id: "learning-development-coordinator",
        title: "Learning & Development Coordinator",
        track: "people",
        summary: "Coordinate training needs, learning programs, content, attendance, feedback, and capability reporting.",
        interestTerms: ["people", "coaching", "learning", "communication", "workplace", "content"],
        industryTerms: ["hr", "education", "consulting", "professional services", "technology"],
        evidenceTerms: ["training", "learning", "facilitation", "content", "coordination", "feedback", "presentation"],
        educationTerms: ["human resources", "education", "psychology", "business", "management", "mba"],
        workStyles: ["Coaching others", "Structured execution", "Customer-facing", "Writing and documentation"],
        expectedWork: ["Coordinate calendars, learners, facilitators, and systems.", "Support needs analysis and learning content.", "Track completion, feedback, and assessment results.", "Improve programs using learner and business evidence."],
        skills: ["Learning coordination", "Training needs analysis", "Facilitation", "Content development", "LMS", "Microsoft Excel"],
    }),
    role({
        id: "implementation-consultant",
        title: "Implementation Consultant",
        track: "technology",
        summary: "Understand customer processes, configure software, coordinate data and testing, and guide successful go-live.",
        interestTerms: ["customer", "technology", "systems", "process", "problem", "consulting"],
        industryTerms: ["saas", "enterprise software", "fintech", "hr tech", "healthcare"],
        evidenceTerms: ["requirements", "customer", "configuration", "api", "testing", "project management", "documentation"],
        educationTerms: ["engineering", "business", "computer science", "information technology", "mba"],
        workStyles: ["Customer-facing", "Problem solving", "Cross-functional", "Structured execution"],
        expectedWork: ["Map customer requirements and current processes.", "Configure workflows and coordinate integrations or data.", "Plan testing, training, and go-live readiness.", "Resolve adoption issues and document decisions."],
        skills: ["Requirements gathering", "Software implementation", "Configuration", "Testing", "Customer training", "Project management"],
    }),
    role({
        id: "quality-assurance-analyst",
        title: "Quality Assurance Analyst",
        track: "technology",
        summary: "Turn requirements into test coverage, find reproducible defects, and protect release quality across user workflows.",
        interestTerms: ["quality", "technology", "systems", "detail", "problem", "product"],
        industryTerms: ["software", "saas", "fintech", "e-commerce", "healthcare"],
        evidenceTerms: ["quality assurance", "testing", "bug", "acceptance criteria", "api", "regression", "documentation"],
        educationTerms: ["engineering", "computer science", "information technology", "business"],
        workStyles: ["Quality and accuracy", "Detail-oriented", "Problem solving", "Structured execution"],
        expectedWork: ["Review requirements and design risk-based test cases.", "Test workflows, APIs, data, and edge conditions.", "Report defects with reproducible evidence.", "Run regression checks and support release decisions."],
        skills: ["Quality assurance", "Test cases", "Regression testing", "Bug reporting", "API testing", "Acceptance criteria"],
    }),
    role({
        id: "technical-support-associate",
        title: "Technical Support Associate",
        track: "technology",
        summary: "Diagnose customer technical issues, communicate clearly, document fixes, and surface product reliability patterns.",
        interestTerms: ["customer", "technology", "systems", "helping", "problem", "quality"],
        industryTerms: ["saas", "enterprise software", "cloud", "cybersecurity", "telecommunications"],
        evidenceTerms: ["support", "troubleshooting", "customer", "api", "logs", "documentation", "incident"],
        educationTerms: ["computer science", "information technology", "engineering", "business"],
        workStyles: ["Customer-facing", "Problem solving", "Detail-oriented", "Fast-paced"],
        expectedWork: ["Clarify issues and reproduce technical symptoms.", "Inspect configurations, logs, data, and integrations.", "Communicate workarounds and resolution progress.", "Document solutions and escalate recurring product problems."],
        skills: ["Troubleshooting", "Technical support", "Log analysis", "REST APIs", "Customer communication", "Documentation"],
    }),
    role({
        id: "content-marketing-associate",
        title: "Content Marketing Associate",
        track: "marketing",
        summary: "Research audiences and create useful content that supports awareness, trust, search, and demand generation.",
        interestTerms: ["writing", "content", "marketing", "brand", "research", "communication"],
        industryTerms: ["media", "saas", "consumer", "education", "professional services"],
        evidenceTerms: ["content", "writing", "seo", "marketing", "research", "social media", "analytics"],
        educationTerms: ["marketing", "communications", "english", "journalism", "business", "mba"],
        workStyles: ["Writing and documentation", "Creative", "Independent research", "Structured execution"],
        expectedWork: ["Research audience questions and content opportunities.", "Write and edit articles, guides, email, or social content.", "Coordinate subject experts, design, and publishing.", "Measure reach, engagement, search, and conversion."],
        skills: ["Content writing", "Content strategy", "SEO", "Editing", "Audience research", "Marketing analytics"],
    }),
    role({
        id: "lifecycle-marketing-associate",
        title: "Lifecycle Marketing Associate",
        track: "marketing",
        summary: "Improve onboarding, engagement, retention, and reactivation through segmented customer communications and experiments.",
        interestTerms: ["marketing", "growth", "customer", "experiment", "data", "communication"],
        industryTerms: ["saas", "e-commerce", "consumer apps", "fintech", "retail"],
        evidenceTerms: ["email", "crm", "onboarding", "retention", "segmentation", "campaign", "funnel", "analytics"],
        educationTerms: ["marketing", "business", "mba", "communications", "analytics"],
        workStyles: ["Analytical", "Creative", "Experimentation", "Structured execution"],
        expectedWork: ["Map customer lifecycle stages and communication gaps.", "Build segmented email, push, or in-product journeys.", "Test messaging, timing, and offers.", "Measure activation, engagement, retention, and reactivation."],
        skills: ["Lifecycle marketing", "CRM", "Segmentation", "Email marketing", "Funnel analysis", "A/B testing"],
    }),
    role({
        id: "sustainability-analyst",
        title: "Sustainability Analyst",
        track: "analytics",
        summary: "Research environmental and social performance, organize ESG data, and support practical sustainability initiatives and reporting.",
        interestTerms: ["sustainability", "social impact", "research", "data", "strategy", "quality"],
        industryTerms: ["renewable energy", "climate tech", "manufacturing", "consulting", "government"],
        evidenceTerms: ["sustainability", "esg", "research", "data analysis", "reporting", "environment", "social impact"],
        educationTerms: ["environment", "economics", "business", "engineering", "sustainability", "mba"],
        workStyles: ["Independent research", "Analytical", "Writing and documentation", "Cross-functional"],
        expectedWork: ["Collect and validate environmental or social data.", "Research standards, risks, and improvement opportunities.", "Support ESG reporting and initiative tracking.", "Translate findings into practical business actions."],
        skills: ["Sustainability", "ESG reporting", "Data analysis", "Research", "Microsoft Excel", "Report writing"],
    }),
];