import type { CandidateProfile, WorkspaceState } from "./types";

export const FAREETH_PROFILE: CandidateProfile = {
    fullName: "Fareeth Raja",
    headline: "Associate Product Manager | AI + FinTech Products | MBA Finance & Marketing",
    email: "fareethraja.26.careers@gmail.com",
    phone: "+91 9159469088",
    location: "India",
    linkedin: "https://www.linkedin.com/in/fareethraja/",
    portfolio: "https://fareeth.vercel.app/",
    github: "https://github.com/fareethraja",
    summary:
        "MBA Finance and Marketing candidate with hands-on product management experience across AI, fintech, trading workflows, payments, onboarding, and user-facing web products. Currently owning product planning and execution for Finverse through a Bermer Software Limited client/product engagement, combining product thinking with technical execution across AI chat, market tools, checkout, admin workflows, and real-time trading features. Strong fit for APM, Product Intern, and Product Analyst roles requiring user problem definition, feature prioritization, product flows, stakeholder communication, metrics thinking, and close collaboration with engineering.",
    sourceText: "",
    skillGroups: [
        {
            id: "skills-product",
            name: "Product Management",
            items: [
                "Product roadmapping",
                "Feature prioritization",
                "User stories",
                "Acceptance criteria",
                "Requirement gathering",
                "Stakeholder communication",
                "Sprint planning basics",
                "Agile and Scrum fundamentals",
                "Business presentation",
                "Market research",
                "User journeys",
            ],
        },
        {
            id: "skills-fintech",
            name: "AI + FinTech Product",
            items: [
                "AI assistant workflows",
                "Azure OpenAI",
                "Multilingual chat UX",
                "Prompt design",
                "Finance workflows",
                "Market data",
                "Stock screeners",
                "Watchlists",
                "Strategy builder",
                "Backtesting",
                "Paper trading",
                "Trading journal",
                "Portfolio and user insight flows",
            ],
        },
        {
            id: "skills-analytics",
            name: "Analytics + Business",
            items: [
                "Product metrics",
                "Funnel thinking",
                "Activation, retention, and conversion basics",
                "Power BI",
                "Microsoft Excel",
                "Data visualization",
                "Financial analysis",
                "Operations management",
                "Recruitment metrics",
            ],
        },
        {
            id: "skills-design",
            name: "Design + Collaboration",
            items: [
                "Figma",
                "UI/UX design",
                "Wireframing",
                "User flows",
                "Canva",
                "Stakeholder-ready product pitches",
                "Documentation",
                "Cross-functional communication",
            ],
        },
        {
            id: "skills-technical",
            name: "Technical Literacy",
            items: [
                "Next.js",
                "React.js",
                "TypeScript",
                "JavaScript",
                "Tailwind CSS",
                "Go",
                "MySQL",
                "REST APIs",
                "WebSocket APIs",
                "Razorpay",
                "Docker",
                "Azure Blob Storage",
                "Vercel",
                "Firebase",
                "Supabase",
                "Git",
                "GitHub",
            ],
        },
    ],
    experiences: [
        {
            id: "experience-finverse",
            role: "Product Manager",
            company: "Finverse Client Engagement via Bermer Software Limited",
            location: "",
            startDate: "Feb 2026",
            endDate: "Present",
            bullets: [
                "Own product planning and execution for Finverse, an AI-powered stock market super app covering Zeno AI, stock screeners, strategy builder, backtesting, paper trading, courses, admin panel, subscription and course checkout, and market-data workflows.",
                "Translate complex finance and trading problems into product flows, user journeys, feature plans, and implementation-ready requirements for AI, payments, learning, market data, and trading simulation modules.",
                "Shaped Zeno AI workflows for multilingual finance queries, chat history, guest limits, IPO, GMP, and market-data enrichment, rate limiting, and tool-grounded AI responses to improve usefulness and trust.",
                "Prioritized and shipped fintech workflows including screeners, watchlists, paper trading journal, PnL handling, candles, quotes, and strategy backtest journeys for retail trading use cases.",
                "Implemented and validated Razorpay course and subscription checkout flows with order validation, signature verification, webhook hardening, coupons, feature flags, and content access controls.",
                "Authored 100+ frontend and backend commits across Next.js and Go repositories, enabling strong collaboration with engineering and faster product iteration.",
                "Improved production readiness through admin tooling, Docker, Azure Blob Storage uploads, CORS origin lockdown, health checks, environment configuration, and deployment wiring.",
            ],
        },
        {
            id: "experience-niyantha",
            role: "Product Intern",
            company: "Bermer Software Limited / Niyantha Transits Private Limited",
            location: "",
            startDate: "Jan 2026",
            endDate: "Present",
            bullets: [
                "Supported product and business presentation work for Niyantha, a hardware and IoT product initiative under Bermer Software Limited.",
                "Contributed to product positioning, stakeholder-facing presentations, and business communication before transitioning into the Finverse client engagement.",
                "Helped convert early product ideas into clearer presentation narratives, roadmap direction, and stakeholder-ready material.",
            ],
        },
        {
            id: "experience-kiddofin",
            role: "Product Manager (Technical)",
            company: "Kiddofin",
            location: "Bengaluru",
            startDate: "Dec 2025",
            endDate: "Jan 2026",
            bullets: [
                "Designed automated email onboarding flows to improve customer activation and first-time user experience.",
                "Led website design and development, translating product goals into user-facing web experiences.",
                "Created product roadmaps, feature plans, and stakeholder-ready product pitches for early product direction.",
            ],
        },
        {
            id: "experience-peunier",
            role: "Human Resource Management Intern",
            company: "Peunier",
            location: "Remote, India",
            startDate: "Dec 2024",
            endDate: "Jan 2025",
            bullets: [
                "Developed job descriptions and posted openings across hiring platforms, improving candidate visibility by 30%.",
                "Screened and interviewed candidates, helping hire 13+ qualified individuals within one month.",
                "Streamlined recruitment workflows using an ATS, reducing hiring time by 25%.",
                "Prepared recruitment metric reports to support future hiring strategy and staffing decisions.",
            ],
        },
    ],
    projects: [
        {
            id: "project-smartslot",
            name: "SmartSlot",
            subtitle: "Mobile-first Dental Appointment PWA",
            dates: "Oct 2025",
            bullets: [
                "Built a mobile-first appointment product for dental students and interns to create daily slots, share booking links through WhatsApp, manage leave days, and track case progress.",
                "Designed around a low-friction patient journey without requiring patient login, using React, Tailwind CSS, Supabase, and Vercel.",
            ],
        },
        {
            id: "project-roomspace",
            name: "RoomSpace",
            subtitle: "Roommate Key Tracker",
            dates: "Aug 2025 - Present",
            bullets: [
                "Built a mobile and web coordination tool to help roommates track who holds the room key with accountability, real-time updates, and offline synchronization.",
                "Focused the product around a simple shared source of truth using React, Tailwind CSS, Node.js, and Firebase.",
            ],
        },
        {
            id: "project-hybrid",
            name: "Hybrid 2.0",
            subtitle: "Sustainable Automobile Concept",
            dates: "Feb 2025 - Present",
            bullets: [
                "Researched and presented a renewable-energy automobile mechanism focused on reducing dependence on fossil fuels and supporting sustainable development.",
                "Used SciSpace, Microsoft Word, PowerPoint, Gemini, ChatGPT, and Perplexity for research, analysis, documentation, and concept development.",
            ],
        },
    ],
    education: [
        {
            id: "education-mba",
            institution: "Krupanidhi College of Management",
            qualification: "MBA in Finance and Marketing",
            dates: "Oct 2024 - Present",
            detail: "CGPA: 8.38/10",
        },
        {
            id: "education-economics",
            institution: "University of Madras (The New College)",
            qualification: "Bachelor of Economics, Gold Medalist",
            dates: "Oct 2021 - Apr 2024",
            detail: "CGPA: 7.16/10",
        },
    ],
    certifications: [
        "Market Research for Product Management - MTF Institute",
        "UI/UX Design and Product Management with Figma - Hudson Dynamic Lab",
        "Microsoft Excel Beginner to Advanced - Udemy",
        "Power BI: Data import, transformation, DAX, dashboards, publishing, and insight sharing",
        "Agile, Scrum, and PMP fundamentals",
    ],
    courses: [],
    achievements: [
        "Gold Medalist in Bachelor of Economics, University of Madras (The New College).",
        "Won first prize for presenting the brand story of Apple among MBA batch 2024-2026 students.",
        "Won first prize for presenting Hybrid 2.0.",
        "Led a team to the finale of the SDG Championship 2022.",
    ],
    additionalSections: [],
};

export const EMPTY_PROFILE: CandidateProfile = {
    fullName: "",
    headline: "",
    email: "",
    phone: "",
    location: "",
    linkedin: "",
    portfolio: "",
    github: "",
    summary: "",
    sourceText: "",
    skillGroups: [
        { id: "skills-core", name: "Core Skills", items: [] },
        { id: "skills-tools", name: "Tools + Technology", items: [] },
    ],
    experiences: [],
    projects: [],
    education: [],
    certifications: [],
    courses: [],
    achievements: [],
    additionalSections: [],
};

function cloneProfile(profile: CandidateProfile): CandidateProfile {
    return JSON.parse(JSON.stringify(profile)) as CandidateProfile;
}

export function createInitialWorkspace(isOwner: boolean): WorkspaceState {
    const profile = cloneProfile(isOwner ? FAREETH_PROFILE : EMPTY_PROFILE);
    return {
        version: 1,
        profile,
        jobs: [],
        latestJobId: "",
        analyses: {},
        resumes: {},
        coverLetters: {},
        plans: [],
        activePlanId: "",
        learningRoadmaps: [],
        activeLearningRoadmapId: "",
        careerPreferences: {
            educationContext: profile.education.map((item) => `${item.qualification}, ${item.institution}`).join("; "),
            interests: isOwner ? "Building useful digital products, AI, fintech, analytics, user experience, and solving business problems" : "",
            interestAreas: isOwner ? ["Building digital products", "Working with data and dashboards", "Finance, investing, and markets", "Technology, software, and systems"] : [],
            workStyles: isOwner ? ["Problem solving", "Cross-functional", "Analytical", "Building"] : [],
            industries: isOwner ? ["FinTech", "SaaS", "AI"] : [],
            targetLevel: "any",
            preferredLocation: isOwner ? "Bengaluru, Chennai, India" : "",
            preferredCountry: isOwner ? "India" : "",
            preferredCities: isOwner ? ["Bengaluru", "Chennai"] : [],
            customLocation: "",
            remotePreference: "any",
            selectedRoleTitles: [],
            targetCompanies: [],
            recencyDays: 7,
        },
        roleSuggestions: [],
        jobSearchResults: [],
        lastJobSearchAt: "",
        offerAnalyses: {},
        activeOfferJobId: "",
    };
}